### ISSUE TITLE
something about 'MAX_NUM_GT_BOXES'

### ISSUE THREAD

**Issue by baolinhu** [guoruoqian/DetNet_pytorch#3]
I want to use your code to train your own dataset. There are many gt boxes in it, and there are probably hundreds of them.`MAX_NUM_GT_BOXES=20`, can I change this parameter a lot? I see the default in Pascal VOC is 20.

**Comment by guoruoqian** [comment]
i think you can change that if you need (if your data gt boxes are less than 20).

**Comment by guoruoqian** [comment]
@baolinhu ,hi

1. if your GT boxes is greater than 20, there will be some boxes ignored.

2.I think if you set ` MAX_NUM_GT_BOXES=100`. it will  train slower and not effect AP.
