### ISSUE TITLE
About Resnet

### ISSUE THREAD

**Issue by hokuto-HIRANO** [guoruoqian/DetNet_pytorch#6]
How did you get a score of resnet?

**Comment by guoruoqian** [comment]
I'm sorry, i can't understand you. I used resnet101 as fpn's backbone

**Comment by hokuto-HIRANO** [comment]
How did you measure the accuracy of resnet 101 (fpn)?
Can I train resnet (fpn) in this repository?

I want to check the result of ResNet-101 (using soft_nms when testing).

Can you understand my English?
I am sorry that I am not good at English.

**Comment by guoruoqian** [comment]
hi, i understand what you mean. You are right.  I trained and tested the resnet101(fpn) use another code in my repositority [FPN_Pytorch](https://github.com/guoruoqian/FPN_Pytorch). Maybe i should merge the two repositority. Sorry

**Comment by hokuto-HIRANO** [comment]
Thank you!
